version: '3'

services:
  web:
    restart: always
    build: ./web
    ports:
      - 5000:5000
    volumes:
      - ./web:/appli
    networks:
      - test-net
    environment:
      SECRET_KEY: postgres
      ENGINE: postgres://postgres:postgres@mydb:5432/data
    depends_on:
      - mydb

  mydb:
    restart: always
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    ports:
      - 5433:5432/tcp
    networks:
      - test-net

  pgadmin:
    restart: always
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - test-net
networks:
  test-net:
    driver: bridge
volumes:
  pgadmin:
    driver: local
  db-data:
    driver: local