version: '3'

services:
  web:
    build: ./web
    depends_on:
      - mydb
    ports:
      - 5000:5000
    volumes:
      - ./web:/appli
    networks:
      - test-net
    environment:
      SECRET_KEY: 7110c8ae51a4b5af97be6534caef90e4bb9bdcb3380af008f90b23a5d1616bf319bc298105da20fe
      ENGINE: postgres://postgres:postgres@mydb:5432/data

  mydb:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    ports:
      - 5433:5432/tcp
    networks:
      - test-net

volumes: 
  db-data:
    driver: local

networks:
  test-net:
    driver: bridge